### ISSUE TITLE
Deploying to production

### ISSUE THREAD

**Issue by chriscn** [chriscn/uoy-week-calendar#3]
How should I deploy this application to production?

- ExpressJS has an [article](https://expressjs.com/en/advanced/best-practice-performance.html).
- [AWS](https://aws.amazon.com/getting-started/hands-on/deploy-nodejs-web-app/) as a PAAS?
- Docker?

Then becomes the issue of where I should deploy it?

- I could host it at home, however I might try and persuade the University to give me some [computing power](https://www.york.ac.uk/it-services/services/linux-hosting/#tab-1).
- Run behind a NGINX proxy with aggressive caching. The underlying data only changes every year.

**Comment by Jbithell** [comment]
Another idea could be to run this nodejs app as a Github Action and it [publishes the individual calendar files to Github Pages](https://github.com/marketplace/actions/deploy-github-pages-site), support for which is now in public beta. This could run each time the repo is updated to ensure the calendars are up to date

**Comment by chriscn** [comment]
> Another idea could be to run this nodejs app as a Github Action and it [publishes the individual calendar files to Github Pages](https://github.com/marketplace/actions/deploy-github-pages-site), support for which is now in public beta. This could run each time the repo is updated to ensure the calendars are up to date

Thanks @Jbithell, I'm going to have a look into that. I would want to host an API for other services to be able to query which might mean I have to actually host it.

Currently looking at dockerising the application but before I do that to prepare it for production:

- Protection middleware (express helmet)
- Logging
- Updating public pages (maybe with templating to keep them up to date, we could even use the api)

**Comment by Jbithell** [comment]
> > Another idea could be to run this nodejs app as a Github Action and it [publishes the individual calendar files to Github Pages](https://github.com/marketplace/actions/deploy-github-pages-site), support for which is now in public beta. This could run each time the repo is updated to ensure the calendars are up to date
> 
> 
> 
> Thanks @Jbithell, I'm going to have a look into that. I would want to host an API for other services to be able to query which might mean I have to actually host it.
> 
> 
> 
> Currently looking at dockerising the application but before I do that to prepare it for production:
> 
> 
> 
> - Protection middleware (express helmet)
> 
> - Logging
> 
> - Updating public pages (maybe with templating to keep them up to date, we could even use the api)
> 
> 

Sounds good - when you say query do you mean as in dynamic responses (e.g. search by week numbers) or query as in subscribe to the calendar on Google calendar etc?

**Comment by chriscn** [comment]
> > > Another idea could be to run this nodejs app as a Github Action and it [publishes the individual calendar files to Github Pages](https://github.com/marketplace/actions/deploy-github-pages-site), support for which is now in public beta. This could run each time the repo is updated to ensure the calendars are up to date
> > 
> > 
> > Thanks @Jbithell, I'm going to have a look into that. I would want to host an API for other services to be able to query which might mean I have to actually host it.
> > Currently looking at dockerising the application but before I do that to prepare it for production:
> > 
> > * Protection middleware (express helmet)
> > * Logging
> > * Updating public pages (maybe with templating to keep them up to date, we could even use the api)
> 
> Sounds good - when you say query do you mean as in dynamic responses (e.g. search by week numbers) or query as in subscribe to the calendar on Google calendar etc?

As in one could send maybe some of the following:
- `GET /api/week?date=2023-01-13` and it would return Spring Week 1 as a string
- `GET /api/year?date=2023-01-13` and it would return a formatted academic year
- `GET /api/weeks?date=2023-01-23` return a JSON object of the academic years weeks. 

Would you want any specific api routes?

**Comment by Jbithell** [comment]
> > > > Another idea could be to run this nodejs app as a Github Action and it [publishes the individual calendar files to Github Pages](https://github.com/marketplace/actions/deploy-github-pages-site), support for which is now in public beta. This could run each time the repo is updated to ensure the calendars are up to date
> > > 
> > > 
> > > Thanks @Jbithell, I'm going to have a look into that. I would want to host an API for other services to be able to query which might mean I have to actually host it.
> > > Currently looking at dockerising the application but before I do that to prepare it for production:
> > > 
> > > * Protection middleware (express helmet)
> > > * Logging
> > > * Updating public pages (maybe with templating to keep them up to date, we could even use the api)
> > 
> > 
> > Sounds good - when you say query do you mean as in dynamic responses (e.g. search by week numbers) or query as in subscribe to the calendar on Google calendar etc?
> 
> As in one could send maybe some of the following:
> 
> * `GET /api/week?date=2023-01-13` and it would return Spring Week 1 as a string
> * `GET /api/year?date=2023-01-13` and it would return a formatted academic year
> * `GET /api/weeks?date=2023-01-23` return a JSON object of the academic years weeks.
> 
> Would you want any specific api routes?

I'd suggest that API routes would be unlikely to be of much use - I can't really see a use case personally, as the performance of manually querying so many dates would be prohibitive. Instead I'd suggest just exposing all the data you have as a json file that can be quickly and easily parsed if needed (although again I don't have an initial use case).

I'd suggest this project essentially exports 4 static files:

- UG calendar
- PG calendar
- Staff calendar 
- JSON file of data (probably keys are dates in a decade and values are the three calendars and what week it is)

Given it's 4 static files that are updated from time-to-time, but have google repeatedly querying them as a subscription, I'd suggest this is perfect for a github pages site, and means you don't need to worry about maintaining a server etc. that will stay up to maintain the subscription.
